-- --------------------------------------------------------

--
-- Table structure for table 'PRODUCT_CATEGORY'
--
DROP TABLE IF EXISTS PRODUCT_CATEGORY;
CREATE TABLE PRODUCT_CATEGORY (
  CATEGORY_ID 		int(20) NOT NULL default '0',
  PARENT_CATEGORY_ID 	int(20) NOT NULL default '0',
  CATEGORY_NAME 	varchar(255) NOT NULL default '',
  ACTIVE_STATUS 	varchar(4) NOT NULL default 'Y',
  PRIMARY KEY  (CATEGORY_ID)
) TYPE=MyISAM;

--
-- Dumping data for table 'PRODUCT_CATEGORY'
--
INSERT INTO PRODUCT_CATEGORY VALUES(0,-1,'All','Y');
INSERT INTO PRODUCT_CATEGORY VALUES(1,0,'Electronics','Y');
INSERT INTO PRODUCT_CATEGORY VALUES(2,0,'Books','Y');
INSERT INTO PRODUCT_CATEGORY VALUES(3,0,'Home & Garden','Y');
INSERT INTO PRODUCT_CATEGORY VALUES(4,1,'Audio & Video ','Y');
INSERT INTO PRODUCT_CATEGORY VALUES(5,1,'Camera & Photo','Y');
INSERT INTO PRODUCT_CATEGORY VALUES(6,1,'Computers','Y');
INSERT INTO PRODUCT_CATEGORY VALUES(7,1,'Software','Y');
INSERT INTO PRODUCT_CATEGORY VALUES(8,2,'Novels','Y');
INSERT INTO PRODUCT_CATEGORY VALUES(9,2,'Entertainment','Y');
INSERT INTO PRODUCT_CATEGORY VALUES(10,2,'Cooking','Y');
INSERT INTO PRODUCT_CATEGORY VALUES(11,6,'Desktops','Y');
INSERT INTO PRODUCT_CATEGORY VALUES(12,6,'Laptops','Y');
